// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkeATws1DK5-wSwVukg02J_arStImB7rc',
    appId: '1:536641137148:android:0e566778a078b5f40e6a79',
    messagingSenderId: '536641137148',
    projectId: 'ceceliacareflutter',
    storageBucket: 'ceceliacareflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9HvnOtWk507csdz89m89qxsc4O4Xgb-c',
    appId: '1:536641137148:ios:0e7cc0924838d5d60e6a79',
    messagingSenderId: '536641137148',
    projectId: 'ceceliacareflutter',
    storageBucket: 'ceceliacareflutter.firebasestorage.app',
    androidClientId: '536641137148-k31ubugla65nia1p61smgj3fmgbm77ne.apps.googleusercontent.com',
    iosClientId: '536641137148-5u9ffsp85s3mfe86feii9fpqdjtghn98.apps.googleusercontent.com',
    iosBundleId: 'com.example.ceceliaCareFlutter',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr5NiVG_iWRXNOogKnLtcpOyFngVXJIQ4',
    appId: '1:536641137148:web:20171286b8d0f9680e6a79',
    messagingSenderId: '536641137148',
    projectId: 'ceceliacareflutter',
    authDomain: 'ceceliacareflutter.firebaseapp.com',
    storageBucket: 'ceceliacareflutter.firebasestorage.app',
    measurementId: 'G-L1MHKYGMCV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9HvnOtWk507csdz89m89qxsc4O4Xgb-c',
    appId: '1:536641137148:ios:0e7cc0924838d5d60e6a79',
    messagingSenderId: '536641137148',
    projectId: 'ceceliacareflutter',
    storageBucket: 'ceceliacareflutter.firebasestorage.app',
    androidClientId: '536641137148-k31ubugla65nia1p61smgj3fmgbm77ne.apps.googleusercontent.com',
    iosClientId: '536641137148-5u9ffsp85s3mfe86feii9fpqdjtghn98.apps.googleusercontent.com',
    iosBundleId: 'com.example.ceceliaCareFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr5NiVG_iWRXNOogKnLtcpOyFngVXJIQ4',
    appId: '1:536641137148:web:5391123c228887de0e6a79',
    messagingSenderId: '536641137148',
    projectId: 'ceceliacareflutter',
    authDomain: 'ceceliacareflutter.firebaseapp.com',
    storageBucket: 'ceceliacareflutter.firebasestorage.app',
    measurementId: 'G-96TRYHW16V',
  );

}